### ISSUE TITLE
main vs master

### ISSUE THREAD

**Issue by richardreeve** [EcoJulia/RandomBooleanMatrices.jl#5]
@mkborregaard - I've just realised that I merged the updated CI workflow for this package and for SpatialEcology to act on the `main` branch. I hadn't noticed that the main branches are still `master`... may be time to switch? Or to fix my error in the workflow of course!

**Comment by mkborregaard** [comment]
Alright. While not a big fan of this type of symbol politics, I also see no reason to be too attached to the past. I've renamed the two master branches to main.

**Comment by richardreeve** [comment]
Yeah, it was just an accident in copy and paste that didn't show up in the PR obviously, rather than a deliberate statement!
